import Head from 'next/head'
import { api } from '../services/api'
import { useEffect, useState } from 'react'
import Image from 'next/image'
import { DataHover, DataMissionManifest, ImageDay } from '../services/types'

export default function Home() {

  const [ dataHover, setDataHover ] = useState<DataHover[]>([])
  
  const [ dataManifestHover, setDataManifestHover ] = useState<DataMissionManifest>({} as DataMissionManifest)
  
  const [ imageDay, setImageDay ] = useState<ImageDay>({} as ImageDay)

  const [ openImageDay, setOpenImageDay ] = useState(false)

  useEffect(() => {
    getMissionManifest()
    getImageDay()
  }, [])

  async function getMissionManifest() {
    const response = await api.post(`/api/nasa`, {
      headers: {
        state: 'mission_manifest'
      }
    })
    setDataManifestHover(response.data.data)
  }

  async function getDataHover() {
    const response = await api.post(`/api/nasa`, {
      headers: {
        state: 'data_hover',
        maxDate: dataManifestHover.max_date
      }
    })
    console.log(response.data)
    setDataHover(response.data.data)
  }
  async function getImageDay() {
    const response = await api.post(`/api/nasa`, {
      headers: {
        state: 'image_day'
      }
    })
    setImageDay(response.data.data)
  }

  return (
    <>
      <Head>
        <title>Home | Travel Space</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col gap-10'>
        <header className='flex items-center bg-blue-800 h-24 text-white text-3xl font-semibold w-full px-10 shadow-headBottomPurple'>
          Travel Space
        </header>

        <div className='flex flex-col  w-full relative text-white'>
          <button onClick={() => setOpenImageDay(!openImageDay)} className='self-center flex p-4 px-10 w-80 rounded-t-2xl border-2 border-blue-900 bg-gray-800/60 hover:bg-gray-800 duration-500 items-start justify-between'>
            View Image 
          </button>
          
          <div className='relative overflow-hidden'>
            <Image alt='' src={imageDay.hdurl} width={1600} height={800} className={'w-full '}/>
            
            <div className='absolute top-0'>
            <div className='absolute top-0 shadow-topShade h-32 -mt-32 z-20 flex'></div>
              <div className={` mx-10 flex flex-col text-3xl font-medium  gap-10 px-10 p-6 pb-8 rounded-b-2xl bg-gray-900/70 overflow-hidden transition-all  duration-1000 ${openImageDay?'-translate-y-[2000px] ' :'translate-y-0'}`}>
                <text className='self-center text-5xl'>{imageDay.title}</text>
                <text className='text-5xl text-blue-700 font-semibold'>{imageDay.copyright}</text>
                <text>{imageDay.date}</text>
                <text className='leading-relaxed text-gray-400'>{'" ' + imageDay.explanation + ' "'}</text>
              </div>
            </div>
          </div>
        </div>

        <section className='flex flex-col items-center gap-16 p-10 font-semibold'>


          <div className='flex gap-6 bg-blue-500/20 text-white'>
            <text>{dataManifestHover.name}</text>
            <text>{dataManifestHover.status}</text>
            <text>{dataManifestHover.launch_date}</text>
            <text>{dataManifestHover.total_photos}</text>
          </div>

          <button onClick={() => getDataHover()} className='p-4 px-10 bg-blue-600 text-white '>
            Request
          </button>

          <div className='grid grid-cols-2 gap-20'>
          { dataHover.map((val) => (
              <div key={val.id} className=''>
                <Image alt='' src={val.img_src} width={600} height={300} className={'max-w-[500px] max-h-[500px] rounded-xl shadow-boxPurple'}/>
              
                <div className='flex justify-between items-center p-6 text-white bg-blue-800 rounded-2xl -mt-2'>
                  <text>{val.earth_date}</text>
                  <text>{val.rover.name}</text>
                  <text>{val.camera.full_name}</text>
                </div>
              </div>
            ))
          }
          </div>
        </section>

        <footer>

        </footer>
      </main>
    </>
  )
}
