import { useEffect, useState } from 'react'
import { Aproach } from '../Components/aproach/Aproach'
import { Header } from '../Components/header/Header'
import { ImageOfDay } from '../Components/imageDay/ImageOfDay'
import { api } from '../services/api'
import { DataMissionManifest, DataRover, ImageDay, NearbyType, RoversType } from '../services/types'

import Head from 'next/head'

import { Division } from '../Components/Divisor'
import { Foot } from '../Components/foot/Foot'
import { Rovers } from '../Components/rovers/Rovers'


export default function Home() {

   const [ rovers, setRovers ] = useState<RoversType[]>([])

   const [ dataManifestHover, setDataManifestHover ] = useState<DataMissionManifest>({} as DataMissionManifest)
   
   const [ imageDay, setImageDay ] = useState<ImageDay>({} as ImageDay)
   
   const [ nearbyObjects, setNearbyObjects ] = useState<NearbyType[]>([])

   useEffect(() => {
      getMissionManifest()
      getImageDay()
      getRovers()
      getNearbyObjects()
   }, [])

   async function getRovers() {
      const response = await api.post(`/api/nasa`, {
         headers: {
         state: 'hovers'
         }
      })

      setRovers(response.data.data)
   }

   async function getMissionManifest() {
      const response = await api.post(`/api/nasa`, {
         headers: {
            state: 'mission_manifest',
            rover: 'curiosity'
         }
      })

      setDataManifestHover(response.data.data)
   }

   async function getImageDay() {
      const response = await api.post(`/api/nasa`, {
         headers: {
         state: 'image_day'
         }
      })

      setImageDay(response.data.data)
   }

   async function getNearbyObjects() {
      const response = await api.post(`/api/nasa`, {
         headers: {
         state: 'nearby'
         }
      })
      setNearbyObjects(response.data.data)
   }

   return (
      <>
      <Head>
         <title>Home | Travel Space</title>
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex flex-col gap-24 items-center'>

         <Header title={'Home'}/>

         <ImageOfDay imageDay={imageDay}/>

         <Division/>

         <section className='flex flex-col items-center gap-24 p-4  sm:p-10 font-semibold'>

            <Rovers rovers={rovers}/>

            <Division/>

            <Aproach nearbyObjects={nearbyObjects}/>    

         </section>

         <Division/>       
         
         <Foot/>
         
      </main>
      </>
   )
}
